In [2]:
import pandas as pd
from sklearn import svm, datasets

In [3]:
df = pd.read_csv("/content/Iris.csv")

In [4]:
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [5]:
df.columns

Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')

In [6]:

X = df.drop(columns=['Id','Species'])
y = df['Species']

In [7]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(X,y, test_size=0.3)

In [8]:
model = svm.SVC(kernel='rbf',C=30,gamma='auto')
model.fit(x_train,y_train)
model.score(x_test,y_test)

0.9777777777777777

**K-fold Cross Validation**

In [9]:
from sklearn.model_selection import cross_val_score

In [10]:
cross_val_score(svm.SVC(kernel = 'linear', C=10, gamma='auto'),X,y,cv=5)

array([1.        , 1.        , 0.9       , 0.96666667, 1.        ])

In [11]:
cross_val_score(svm.SVC(kernel = 'linear', C=20, gamma='auto'),X,y,cv=5)

array([1.        , 1.        , 0.9       , 0.93333333, 1.        ])

In [12]:
cross_val_score(svm.SVC(kernel = 'linear', C=30, gamma='auto'),X,y,cv=5)

array([1. , 1. , 0.9, 0.9, 1. ])

In [13]:
import numpy as np
kernels = ['rbf','linear']
C = [10,20,30]
avg_scores = {}
for kval in kernels:
    for cval in C:
        cv_scores = cross_val_score(svm.SVC(kernel=kval, C=cval, gamma='auto'), X, y, cv=5)
        avg_scores[kval + '-' + str(cval)] = np.average(cv_scores)

avg_scores

{'rbf-10': 0.9800000000000001,
 'rbf-20': 0.9666666666666668,
 'rbf-30': 0.96,
 'linear-10': 0.9733333333333334,
 'linear-20': 0.9666666666666666,
 'linear-30': 0.96}

In [14]:
from sklearn.model_selection import GridSearchCV

clf = GridSearchCV(svm.SVC(gamma = 'auto'), {
    'C' : [10,20,30],
    'kernel' : ['rbf','linear']

}, cv=5, return_train_score=False)


clf.fit(x_train,y_train)
clf.cv_results_

{'mean_fit_time': array([0.00277915, 0.00229044, 0.00221796, 0.0022408 , 0.00228982,
        0.00214014]),
 'std_fit_time': array([5.74691308e-04, 1.70978832e-04, 5.46910394e-05, 1.39703897e-04,
        1.50785937e-04, 1.06673066e-05]),
 'mean_score_time': array([0.00187616, 0.00195422, 0.00163016, 0.00165653, 0.00165243,
        0.0016511 ]),
 'std_score_time': array([1.83059356e-04, 5.76718795e-04, 2.15135483e-05, 5.69637820e-05,
        6.35612306e-05, 1.23195879e-04]),
 'param_C': masked_array(data=[10, 10, 20, 20, 30, 30],
              mask=[False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear'],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'},
  {'C': 30, 'kernel': 'rbf'},
  {'C': 30, 'kernel': 'linear'}],
 'split0_test_score': array([1., 1., 1., 1., 1., 1.]),
 'split1_test_score': array([0.9047619 , 0.95238095, 0.9047619 , 0.9047619 , 0.9047619 ,
        0.9047619 ]),
 'split2_test_score': array([0.9047619, 0.9047619, 0.9047619, 0.9047619, 0.9047619, 0.9047619]),
 'split3_test_score': array([1.        , 0.95238095, 0.95238095, 0.95238095, 0.95238095,
        0.95238095]),
 'split4_test_score': array([1.        , 1.        , 1.        , 1.        , 1.        ,
        0.95238095]),
 'mean_test_score': array([0.96190476, 0.96190476, 0.95238095, 0.95238095, 0.95238095,
        0.94285714]),
 'std_test_score': array([0.04665695, 0.03563483, 0.04259177, 0.04259177, 0.04259177,
        0.03563483]),
 'rank_test_score': array([1, 1, 3, 3, 3, 6], dtype=int32)}

In [15]:
df = pd.DataFrame(clf.cv_results_)
df

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.002779,0.000575,0.001876,0.000183,10,rbf,"{'C': 10, 'kernel': 'rbf'}",1.0,0.904762,0.904762,1.000000,1.000000,0.961905,0.046657,1
1,0.002290,0.000171,0.001954,0.000577,10,linear,"{'C': 10, 'kernel': 'linear'}",1.0,0.952381,0.904762,0.952381,1.000000,0.961905,0.035635,1
2,0.002218,0.000055,0.001630,0.000022,20,rbf,"{'C': 20, 'kernel': 'rbf'}",1.0,0.904762,0.904762,0.952381,1.000000,0.952381,0.042592,3
3,0.002241,0.000140,0.001657,0.000057,20,linear,"{'C': 20, 'kernel': 'linear'}",1.0,0.904762,0.904762,0.952381,1.000000,0.952381,0.042592,3
4,0.002290,0.000151,0.001652,0.000064,30,rbf,"{'C': 30, 'kernel': 'rbf'}",1.0,0.904762,0.904762,0.952381,1.000000,0.952381,0.042592,3
5,0.002140,0.000011,0.001651,0.000123,30,linear,"{'C': 30, 'kernel': 'linear'}",1.0,0.904762,0.904762,0.952381,0.952381,0.942857,0.035635,6

In [16]:
df[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0       10          rbf         0.961905
1       10       linear         0.961905
2       20          rbf         0.952381
3       20       linear         0.952381
4       30          rbf         0.952381
5       30       linear         0.942857

In [17]:
dir(clf)

['__abstractmethods__',
 '__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__sklearn_clone__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_build_request_for_signature',
 '_check_feature_names',
 '_check_n_features',
 '_check_refit_for_multimetric',
 '_doc_link_module',
 '_doc_link_template',
 '_doc_link_url_param_generator',
 '_estimator_type',
 '_format_results',
 '_get_default_requests',
 '_get_doc_link',
 '_get_metadata_request',
 '_get_param_names',
 '_get_routed_params_for_fit',
 '_get_scorers',
 '_get_tags',
 '_more_tags',
 '_parameter_constraints',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_required_parameters',
 '_run_search',
 '_select_best_index',
 '_sk_visual_block_',
 '_validate_data',
 '_validate_params',
 'best_estimator_',
 'best_index_',
 'best_params_',
 'best_score_',
 'classes_',
 'cv',
 'cv_results_',
 'decision_function',
 'error_score',
 'estimator',
 'feature_names_in_',
 'fit',
 'get_metadata_routing',
 'get_params',
 'inverse_transform',
 'multimetric_',
 'n_features_in_',
 'n_jobs',
 'n_splits_',
 'param_grid',
 'pre_dispatch',
 'predict',
 'predict_log_proba',
 'predict_proba',
 'refit',
 'refit_time_',
 'return_train_score',
 'score',
 'score_samples',
 'scorer_',
 'scoring',
 'set_params',
 'transform',
 'verbose']

In [18]:
clf.best_score_

0.9619047619047618

# **Choose Best Model**

In [19]:
from sklearn import svm
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression